module.exports = (
  testsInSuite,
  totalCompleted,
  expectedResults,
  unexpectedResults,
  flakyTests,
  testMarkedSkipped,
  failureFree,
  duration,
  avgTestDuration,
  formattedDuration,
  formattedAvgTestDuration,
) => `
Total Tests in Suite: ${testsInSuite},
Total Tests Completed: ${totalCompleted},
Tests Passed: ${expectedResults},
Tests Failed: ${unexpectedResults},
Flaky Tests: ${flakyTests},
Test Skipped: ${testMarkedSkipped},
Test run was failure free? ${failureFree},
Duration in ms: ${duration},
Average Test Duration:${avgTestDuration},
Formatted Duration: ${formattedDuration},
Formatted Avg Test Duration: ${formattedAvgTestDuration}`;
